### PR TITLE
DONE: READMEs + Test shortcuts + Fixes

### PR DESCRIPTION
**Pull request by Neketek**
The main README explains everything

### CODE REVIEW

**Comment by Neketek** [comment]
https://github.com/gs-gs/ha-igl-p2/issues/349

**Comment by Neketek** [comment]
@koriaf Please, merge.

**Review by koriaf — APPROVED** [review]
the documentation looks good, will try it locally

**Comment by koriaf** [comment]
okay, it got built and messages are flowing (at least partially, didn't test it in full)

**Pull request merged**
