### PR TITLE
Dockerization

### PR DESCRIPTION
**Pull request by Neketek**
I spent quite a lot of time trying to align everything to work as one big project rather than a collection of small independent ones. Now all subprojects are adequately connected and can communicate. Most of the time was spent on the contract deployer and accessibility of its build artifacts through S3 interface. 
List of services:
1. channel-api - exposes contract interface via REST api.
1. websub-hub - provides websub functionality for channel-api service
    1. API server
    1. callback-spreader-processor
    1. callback-delivery-processor
    1. new-message-observer-processor
1. contract-event-listener - used to reroute contract events to more common event sources like SQS.
1. contract-deployer - used to automatically deploy/update ChannelNode contract on a specified blockchain
1. localstack - used for AWS emulation
1. ganache - used for ethereum emulation

In total, we have 14 services(because for testing purposes, we need two channels) + 2 emulators. 
Next steps:
1. Merging of the websub-hub and the channel-api. Should reduce the complexity and number of services we have in the setup.
1. System test
1. Update of the integration tests for services that lost them due to the changes in docker-compose configuration

Additionally, I added unlock file mechanics to all services that depend on specific procedures. This makes local dev env stable by making services startup linear where it's needed.

@roleyfoley @monkeypants If nothing is deployed yet we can safely merge this project setup into master and I will continue my work on final touches.

### CODE REVIEW

**Comment by Neketek** [comment]
Related issues https://github.com/gs-gs/ha-igl-p2/issues/326 https://github.com/gs-gs/ha-igl-p2/issues/246

**Comment by monkeypants** [comment]
```
...
[Pipeline] End of Pipeline
[GitHub Checks] Causes for no suitable publisher found: 
[GitHub Checks] Trying to resolve checks parameters from Git SCM...
[GitHub Checks] Job does not use Git SCM
[GitHub Checks] Trying to resolve checks parameters from GitHub SCM...
[GitHub Checks] No GitHub app credentials found: 'github'
[GitHub Checks] See: https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc
[Checks API] No suitable checks publisher found.

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
```
Was this a problem caused by @Neketek or by changes to Jenkins?

**Comment by Neketek** [comment]
@monkeypants I deleted the old Jenkins file because it will fail due to the project structure reorganization. If you want, I can play with it and recreate its functionality with recent updates in mind. But I think that this Jenkins task is not relevant now. At first, I need to create system and integration tests, and then we can talk about the Jenkins task that will perform checks and builds. + Due to the possible merging of the websub-hub and channel-api the Jenkins task can change.

**Comment by roleyfoley** [comment]
@Neketek The jenkins file is what makes this code deploy into the environment. So it shouldn't have been removed. We can skip the testing stages and remove them but this is required. Otherwise the code will never see the light of our deployed environment

**Comment by Neketek** [comment]
@roleyfoley But I specifically asked about this project deployment state, and as far as I remember you told me that nothing is deployed yet.

**Comment by roleyfoley** [comment]
It's in a bit of a zombie state, parts of it are and parts of it aren't. 

But I's rather start from something than nothing and we will need the Jenkinsfile to deploy it anyway

**Comment by Neketek** [comment]
@roleyfoley Ok, then let's merge it. After that I will complete tests and create shortcuts for the build artifacts creation. Then you will be able to recreate the Jenkins file in no time.

**Comment by Neketek** [comment]
@monkeypants Please merge it into master.

**Pull request merged**
